package dev.diena.anion.features.starship

import dev.diena.anion.extensions.blockPos
import it.unimi.dsi.fastutil.shorts.Short2ObjectOpenHashMap
import net.minecraft.core.SectionPos
import net.minecraft.core.Vec3i
import net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket
import net.minecraft.server.level.ServerLevel
import net.minecraft.world.level.block.Blocks
import net.minecraft.world.level.block.state.BlockState

/**
 *
 *  full disclosure: this file was entirely generated by Sonnet 4.6 from Anthropic
 *
 *  the entire Starship class was written by a human, but this human really hates networking.
 *
 *  TODO: move iteration/packet generation calls into main starship move loop to prevent duplicate calls
 *
 * */
object StarshipPackets {

    fun sendSections(

        level: ServerLevel,
        newPositions: Set<Vec3i>,
        oldPositions: Set<Vec3i>,
        newBlockMap: Map<Vec3i, BlockState>

    ) {

        val changes = HashMap<SectionPos, Short2ObjectOpenHashMap<BlockState>>()

        for (vec in oldPositions) {

            val sec = SectionPos.of(vec.blockPos)
            changes.getOrPut(sec) { Short2ObjectOpenHashMap() }[SectionPos.sectionRelativePos(vec.blockPos)] =
                Blocks.AIR.defaultBlockState()

        }

        for (vec in newPositions) {

            val sec = SectionPos.of(vec.blockPos)
            changes.getOrPut(sec) { Short2ObjectOpenHashMap() }[SectionPos.sectionRelativePos(vec.blockPos)] =
                newBlockMap[vec] ?: Blocks.AIR.defaultBlockState()

        }

        for ((secPos, blockMap) in changes) {

            val packet = ClientboundSectionBlocksUpdatePacket(secPos, blockMap)
            level.chunkSource.chunkMap.getPlayers(secPos.chunk(), false).forEach { player ->
                player.connection.send(packet)
            }

        }

    }

}
